apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "x-api-adapter.fullname" . }}-config
  labels:
    {{- include "x-api-adapter.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
