apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "x-api-adapter.fullname" . }}
  labels:
    {{- include "x-api-adapter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "x-api-adapter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "x-api-adapter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "x-api-adapter.fullname" . }}-config
            - secretRef:
                name: {{ .Values.credentialsSecretName }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: actuator
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
