apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chrome-vnc.fullname" . }}
  labels:
    {{- include "chrome-vnc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "chrome-vnc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chrome-vnc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chrome-vnc.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: cdp
              containerPort: 9222
              protocol: TCP
            - name: novnc
              containerPort: 6080
              protocol: TCP
          volumeMounts:
            - name: chrome-profile
              mountPath: /chrome-profile
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: chrome-profile
          persistentVolumeClaim:
            claimName: {{ include "chrome-vnc.fullname" . }}-pvc