apiVersion: v1
kind: Service
metadata:
  name: {{ include "chrome-vnc.fullname" . }}-headless
  labels:
    {{- include "chrome-vnc.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: false
  ports:
    - name: cdp
      port: 9222
      targetPort: 9222
      protocol: TCP
  selector:
    {{- include "chrome-vnc.selectorLabels" . | nindent 4 }}
