apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sweeper-agent.fullname" . }}-pvc
  labels:
    {{- include "sweeper-agent.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.chromeProfile.storageSize | default "2Gi" }}