apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sweeper-agent.serviceAccountName" . }}
  labels:
    {{- include "sweeper-agent.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.gcpServiceAccount }}
iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccount }}
{{- end }}