replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/adlt-s26/adlt-s26-repo/x-sweeper-web
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /api/health
    port: http
  initialDelaySeconds: 3
  periodSeconds: 10