"use client";

import { Box, Card, Container, Divider, Group, Select, Stack, Switch, Text, ThemeIcon } from "@mantine/core";
import { IconAdjustments, IconRobot, IconUsersGroup } from "@tabler/icons-react";
import { useSweepSettings } from "@/components/SweepSettingsProvider";

export default function ConfigPage() {
  const { autoUnfollow, sweepCount, ready, updateSettings } = useSweepSettings();

  return (
    <Box bg="gray.2" mih="calc(100dvh - var(--app-shell-header-height, 46px) - var(--app-shell-footer-height, 74px))">
      <Container size="sm" bg="white" mih="calc(100dvh - var(--app-shell-header-height, 46px) - var(--app-shell-footer-height, 74px))" pb="xl">
        <Box
          pos="sticky"
          bg="white"
          mx="calc(-1 * var(--mantine-spacing-md))"
          px="md"
          style={{ top: "var(--app-shell-header-height, 46px)", zIndex: 5 }}
        >
          <Group gap={6} py="xs">
            <IconAdjustments size={18} color="var(--mantine-color-gray-6)" />
            <Text fw="bold">Sweep Configuration</Text>
          </Group>
          <Divider mx="calc(-1 * var(--mantine-spacing-md))" />
        </Box>

        <Stack gap="md" mt="md" data-testid="settings-page" data-settings-ready={ready ? "true" : "false"}>
          <Text size="sm" c="dimmed">
            These settings are used for every new sweep and are saved in this browser.
          </Text>

          <Card withBorder radius="md" padding="md">
            <Group justify="space-between" align="flex-start" wrap="nowrap" gap="md">
              <Group align="flex-start" wrap="nowrap" gap="sm" style={{ flex: 1 }}>
                <ThemeIcon variant="light" color="orange" radius="xl" size="lg">
                  <IconRobot size={19} />
                </ThemeIcon>
                <Box>
                  <Text fw={600} size="sm">Auto-unfollow</Text>
                  <Text size="xs" c="dimmed" mt={2}>
                    Automatically apply every UNFOLLOW recommendation generated by a sweep.
                  </Text>
                </Box>
              </Group>
              <Switch
                aria-label="Auto-unfollow"
                color="orange"
                checked={autoUnfollow}
                disabled={!ready}
                onChange={(event) => updateSettings({ autoUnfollow: event.currentTarget.checked })}
                data-testid="auto-unfollow"
              />
            </Group>
          </Card>

          <Card withBorder radius="md" padding="md">
            <Group align="flex-start" wrap="nowrap" gap="sm">
              <ThemeIcon variant="light" radius="xl" size="lg">
                <IconUsersGroup size={19} />
              </ThemeIcon>
              <Box style={{ flex: 1 }}>
                <Text fw={600} size="sm">Accounts per sweep</Text>
                <Text size="xs" c="dimmed" mt={2} mb="sm">
                  Choose how many accounts the agent should review in each new sweep, up to 500.
                </Text>
                <Select
                  aria-label="Accounts per sweep"
                  data={[
                    { value: "3", label: "3 accounts" },
                    { value: "10", label: "10 accounts" },
                    { value: "20", label: "20 accounts" },
                    { value: "30", label: "30 accounts" },
                    { value: "50", label: "50 accounts" },
                    { value: "100", label: "100 accounts" },
                    { value: "200", label: "200 accounts" },
                    { value: "500", label: "500 accounts" },
                  ]}
                  value={String(sweepCount)}
                  disabled={!ready}
                  onChange={(value) => value && updateSettings({ sweepCount: Number(value) })}
                  allowDeselect={false}
                  data-testid="sweep-count"
                />
              </Box>
            </Group>
          </Card>
        </Stack>
      </Container>
    </Box>
  );
}
